### PR TITLE
Docs examples

### PR DESCRIPTION
**Pull request by machow**
This PR adds an extremely rudimentary docs site. I realized there are a ton of examples throughout the R gt docs, and it was helpful to try recreating some!

I also added support for using a polars DataFrame when groupname_cols is passed!

### CODE REVIEW

**Comment by machow** [comment]
@rich-iannone no rush on this, but it looks like one of the tables doesn't quite render correctly. I wonder if the rowname and groupname col needs to be removed from the rendered table? (OR ACTUALLY, maybe it's because I accidentally had the spanner go over the rowname and groupname col 😱)

image

Here's the code I used:

```python
from great_tables import GT, countrypops

import polars as pl
import polars.selectors as cs

# Get vectors of 2-letter country codes for each region of Oceania
countries = {
    "Australasia": ["AU", "NZ"],
    "Melanesia":  ["NC", "PG", "SB", "VU"],
    "Micronesia": ["FM", "GU", "KI", "MH", "MP", "NR", "PW"],
    "Polynesia": ["PF", "WS", "TO", "TV"],
}

# a dictionary mapping region to country (e.g. AU -> Australasia)
region_to_country = {
    region: country
    for country, regions in countries.items()
    for region in regions
}

keep_rows = (
    countrypops.country_code_2.isin(list(region_to_country))
    & countrypops.year.isin([2000, 2010, 2020])
)

# Create a gt table based on a preprocessed `countrypops`
wide_pops = (
    pl.from_pandas(countrypops)
    .filter(
        pl.col("country_code_2").is_in(list(region_to_country))
        & pl.col("year").is_in([2000, 2010, 2020])
    )
    .with_columns(
        pl.col("country_code_2")
        .map_dict(region_to_country)
        .alias("region")
    )
    .pivot(
        index=["country_name", "region"],
        columns="year",
        values="population"
    )
    .sort("2020", descending=True)
)

(
    GT(wide_pops, rowname_col = "country_name", groupname_col = "region")
    .tab_header(title ="Populations of Oceania's Countries in 2000, 2010, and 2020")
    .tab_spanner(
        label = "Total Population",
        columns = cs.all()
    )
    .fmt_integer()
)
```

**Comment by machow** [comment]
Feel free to merge as is or chuck any rendering fixes here!

**Comment by rich-iannone** [comment]
I noticed the spanner bug myself (made this issue: https://github.com/posit-dev/great-tables/issues/41). Going to fix that very soon, then your example should work!

**Review by rich-iannone — APPROVED** [review]
LGTM!

**Pull request merged**
