### PR TITLE
Refactor `fmt_time`, `fmt_date` and `fmt_datetime`

### PR DESCRIPTION
**Pull request by jrycw**
Related to #222 , I'm thinking we could possibly delegate the validation of lifts to the built-in `datetime.datetime.fromisoformat` function.

Fixes: #299

### CODE REVIEW

**Comment by machow** [comment]
@rich-iannone can you verify that `datetime.fromisoformat()` handles the cases you were thinking of? Can you be sure to enumerate in a comment the cases you try (for posterity)?

**Comment by rich-iannone** [comment]
I mostly wanted to make sure that `datetime.fromisoformat()` handled most of the common cases and I found it's quite capable. The following input variations results in correct (the same) output:

```{python}
import datetime
from great_tables import vals

iso_str = [
    "2020-05-20",
    "2020-05-20 22:30",
    "2020-05-20T22:30",
    "2020-05-20 22:30:05",
    "2020-05-20 22:30:05.824" # milliseconds *must* have 3 decimal places
    ]

fmtd_dates = []

for val in iso_str:
    fmtd_dates.append((vals.fmt_date(datetime.datetime.fromisoformat(val), date_style="wd_m_day_year"))[0])

fmtd_dates
```

```
['Wed, May 20, 2020',
 'Wed, May 20, 2020',
 'Wed, May 20, 2020',
 'Wed, May 20, 2020',
 'Wed, May 20, 2020']
```

So I think the code change is great here. Thanks, @jrycw !

**Comment by jrycw** [comment]
> I mostly wanted to make sure that `datetime.fromisoformat()` handled most of the common cases and I found it's quite capable. The following input variations results in correct (the same) output:
> 
> ```
> import datetime
> from great_tables import vals
> 
> iso_str = [
>     "2020-05-20",
>     "2020-05-20 22:30",
>     "2020-05-20T22:30",
>     "2020-05-20 22:30:05",
>     "2020-05-20 22:30:05.824" # milliseconds *must* have 3 decimal places
>     ]
> 
> fmtd_dates = []
> 
> for val in iso_str:
>     fmtd_dates.append((vals.fmt_date(datetime.datetime.fromisoformat(val), date_style="wd_m_day_year"))[0])
> 
> fmtd_dates
> ```
> 
> ```
> ['Wed, May 20, 2020',
>  'Wed, May 20, 2020',
>  'Wed, May 20, 2020',
>  'Wed, May 20, 2020',
>  'Wed, May 20, 2020']
> ```
> 
> So I think the code change is great here. Thanks, @jrycw !

Please correct me if I'm mistaken, but it seems you're testing `fmt_date` instead of `fmt_datetime`. Since `vals.fmt_datetime` isn't available, it needs to be tested from `GT`.

**Comment by rich-iannone** [comment]
@jrycw you are right. I mistakenly thought that `.fmt_date()` used the same internal function. I checked out this branch and tried out some variations. I found that this could be further improved if there is a single validation and transformation from `datetime.fromisoformat(x)` (we could drop the use of `_validate_iso_datetime_str()`).

With that change, the following code works:

```
import datetime
from great_tables import GT
import polars as pl

df = pl.DataFrame({"x": [
    "2020-05-20",
    "2020-05-20 22:30",
    "2020-05-20T22:30",
    "2020-05-20 22:30:05",
    "2020-05-20T22:30:05.232" # milliseconds *must* have 3 decimal places
    ]})

GT(df).fmt_datetime(columns="x", date_style="wd_m_day_year", time_style="h_m_p")
```

It produces this:
fmt_datetime_refactor_tbl

This seems like a good improvement because the first and last cases failed before, but they provide formatted output now (and they work as can be expected).

To do this, I renamed `_iso_to_datetime()` to `_iso_str_to_datetime()` with this changed it to:

```python
def _iso_str_to_datetime(x: str) -> datetime:
    """
    Converts a string in ISO format to a datetime object.

    Args:
        x (str): The string to be converted.

    Returns:
        datetime: The converted datetime object.
    """
    return datetime.fromisoformat(x)
```

The code in `fmt_datetime()` changes to:

```python

        # If `x` is a string, assume it is an ISO datetime string and convert it to a datetime object
        if isinstance(x, str):

            # Convert the ISO datetime string to a datetime object
            x = _iso_str_to_datetime(x)
```

@jrycw @machow does this change make sense? I could push the changes to the branch (or you could modify). Also, some new test cases are needed here.

**Comment by jrycw** [comment]
LGTM! If @machow is also on board with this, could @rich-iannone push your changes to the branch? I'll then proceed to add the relevant tests based on your demonstration.

**Comment by machow** [comment]
This sounds good to me!

**Comment by jrycw** [comment]
It turns out we could make similar modifications to `fmt_date`. Here's a summary of the changes:
* Removed `_validate_iso_date_str`.
* Added `_iso_str_to_date`.
* Retained `_iso_to_date` (since `_generate_data_vals` relies on this function).
* Added `test_fmt_date`.

I believe the modifications are correct, but please feel free to correct any mistakes I may have made.

**Comment by jrycw** [comment]
I attempted to remove `_iso_to_date` and replace it with `_iso_str_to_date` in `_generate_data_vals`, and it seems to have worked.

**Review by rich-iannone — APPROVED** [review]
LGTM!

**Pull request merged**
