### PR TITLE
Refactor nanoplots

### PR DESCRIPTION
**Pull request by machow**
This PR is for reviewing the nanoplots code, which we punted on in the name of getting it out the door!

### CODE REVIEW

**Comment by machow** [comment]
@rich-iannone do you mind picking this up when you get the chance?

**Comment by rich-iannone** [comment]
> @rich-iannone do you mind picking this up when you get the chance?

For sure! Thanks for going over all of this :)

**Comment by machow** [comment]
@rich-iannone todo:

* Split up all the cases in the test nanoplot output into individual tests (the test names should reflect what is being tested).
* Remove xfail mark for cases where `pytest.raises` is being used to test something being raised.

Ping when it's ready and we can get it merged!

**Comment by machow** [comment]
LGTM--thanks for this, loving that sweet sweet test coverage!

**Pull request merged**
