### PR TITLE
Improve test coverage for `test_options.py`

### PR DESCRIPTION
**Pull request by jrycw**
This PR aims to improve the test coverage for `test_options.py`. I hope it helps!

### CODE REVIEW

**Review by machow — APPROVED** [review]
This looks like a helpful bit of cleanup, thanks!

**Comment by machow** [comment]
@rich-iannone do you want to glance over / merge?

**Review by rich-iannone — APPROVED** [review]
LGTM!

**Comment by rich-iannone** [comment]
Thanks @jrycw ! This is a good refactor and the additional test coverage helps a lot :) I'll merge now.

**Pull request merged**
