### PR TITLE
Standardizing code style for checking container emptiness

### PR DESCRIPTION
**Pull request by jrycw**
This PR aims to standardize the code style for checking container emptiness. Relevant discussion can be found in issue #194.

Additionally, I noticed the pattern `if len(container)`, and initially planned to replace it with `if container`, which feels more intuitive to me than `if len(container) != 0`.  However, it appears that this modification would result in breaking too many tests, so I will leave it unchanged for now.

### CODE REVIEW

**Comment by machow** [comment]
Thanks for submitting! It's helpful for me to have to think explicitly about these choices!

> Additionally, I noticed the pattern if len(container), and initially planned to replace it with if container, which feels more intuitive to me than if len(container) != 0. However, it appears that this modification would result in breaking too many tests, so I will leave it unchanged for now.

Do you mind pointing me to a place where this happened? I'm guessing it was for a custom class?

**Comment by jrycw** [comment]
> Thanks for submitting! It's helpful for me to have to think explicitly about these choices!
> 
> > Additionally, I noticed the pattern if len(container), and initially planned to replace it with if container, which feels more intuitive to me than if len(container) != 0. However, it appears that this modification would result in breaking too many tests, so I will leave it unchanged for now.
> 
> Do you mind pointing me to a place where this happened? I'm guessing it was for a custom class?

There should be four places where the pattern `if len(container)` is used. You can review the final revert commit [here](https://github.com/posit-dev/great-tables/pull/199/commits/a5398228d5e9f280edbdeb26fe05b92774818f71). 

Meanwhile, you can check the test fail log, which should be available somewhere like [here](https://github.com/posit-dev/great-tables/actions/runs/7914142787/job/21603274713). It should be something like:
``` python
ERROR tests/test_gt.py::test_gt_replace - ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
ERROR tests/test_gt.py::test_gt_object_prerender - ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
ERROR tests/test_gt.py::test_gt_table_render - ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by machow** [comment]
Ah thanks for pointing to the code! I think this is the issue discussed in this [SO post](https://stackoverflow.com/a/9381545/1144523) (they focus on numpy, but same concept; arrays in data libraries raise errors on `__bool__`).

**Comment by jrycw** [comment]
Thanks for sharing the details. Do you think we should stick with the current approach or switch to `if len(container) != 0`? Or do you have any other ideas?

**Comment by machow** [comment]
I've been thinking through these kinds of checks, and how they work with data tools. If it's okay with you, I feel okay with leaving the original code as is. Thanks for flagging the need for consistency, and digging into this code. It was really helpful to have to read about these checks, PEP 8, and how this works with DataFrames/Series, etc..

It seems okay to leave as is, since we're a fairly data centric library, and I suspect I adopted these practices in part because they work with data arrays etc..

**Pull request closed without merging**
