### PR TITLE
fix: better error for list data fmt_nanoplot

### PR DESCRIPTION
**Pull request by marcozzxx810**
# Summary

add a type check for data column, so that only scalar value is passed.

*will add a pytest* but want to make sure this is expected.

# Related GitHub Issues and PRs

- Ref: #331

# Checklist

- [x] I understand and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/).
- [x] I have followed the [Style Guide for Python Code](https://peps.python.org/pep-0008/) as best as possible for the submitted code.
- [x] I have added **pytest** unit tests for any new functionality.

### CODE REVIEW

**Comment by machow** [comment]
Hey, thanks for taking this up! It seems like the challenge in #331 might be:

* fmt_nanoplot current accepts [two plot types](https://github.com/marcozzxx810/great-tables/blob/b749a7bac0792109611632cbeff4b6c1076a4c13/great_tables/_formats.py#L62-L64): line, bar
* these types work with scalars. E.g. bar produces a single sideways bar.
* however, invalid plot_types seem to be allowed through. For examples bars (or maybe even barsabcdefg) don't raise an error :/.

I wonder if just validating that plot_type is in the list of plot_type options would be enough to resolve the issue? I'm happy to take it up, or if you want to take a swing at it, I'm happy to review!

**Comment by marcozzxx810** [comment]
Hi @machow, I have updated the code but CI Test seems to failed in main as well. 

It will be great that if you can let me know how to resolve.

**Comment by rich-iannone** [comment]
I can reproduce this on my system *after* upgrading Polars to version `0.20.28`.

**Review by machow — APPROVED** [review]
This looks great, thanks so much for submitting this PR! These kinds of warnings seem really important for avoiding surprising issues due to typos. This LGTM -- Rich do you want to merge?

**Pull request merged**
