### PR TITLE
Fix render reorder causing incorrect groupings

### PR DESCRIPTION
**Pull request by machow**
Currently, Great Tables keeps a GT._body.body dataframe, ordered to match the final output (e.g. sorted by group). This means that what happens currently looks like this:

1. formatters run, put results on GT._body.body
2. GT._build_data() returns a new GT object, with `._body.body` reordered to match final output
3. GT.render_as_html() -> create_body_component_h() : attempts to set any missing values in ._body.body to a string version of the original data. This is to fill in any unformatted values.

However, there are two issues with this:

* We attempt to grab rows from `_body.body` when rendering html, as if the dataframe hasn't been sorted. (but it has).
* With polars, we are accidentally filling in missing values in step (3) with the original data, in its original order.

In order to fix this, we need to decide whether `_body.body` should be sorted, and make sure it's filled consistently across pandas and polars.

This PR simply removes the sorting of `_body.body`. Since we index based on the original data (e.g. passing `row=1` to a formatter refers to that row position in the original, unsorted data), it seems like we can avoid sorting `._body.body`, and just grab the correctly ordered rows when rendering.

(Note that the snapshot test I added when addressing #201 was wrong 😭, and I fixed it here)

Fixes: https://github.com/posit-dev/great-tables/issues/98

### CODE REVIEW

**Comment by machow** [comment]
Shoot, I checked out this branch from the formatter PR one. Once that's merged I'll just get this one caught up, so it's less chaotic!

**Comment by rich-iannone** [comment]
> Shoot, I checked out this branch from the formatter PR one. Once that's merged I'll just get this one caught up, so it's less chaotic!

The formatter PR has been reviewed (great work!) so it can be merged.

**Comment by machow** [comment]
Alright, it should now just show the diff against main (no fmt method changes)! Note that this PR makes a fairly substantial change of keeping `_body.body` in the original input order. This means nothing gets reordered, only that the renderer func grabs rows in final display order.

Definitely let me know if this will cause issues in the future, based on any gt for R behaviors!

**Review by rich-iannone — APPROVED** [review]
Looks great! Thank you!

**Pull request merged**
