### PR TITLE
docs: add a preview section for the built-in datasets

### PR DESCRIPTION
**Pull request by jrycw**
I’d like to propose adding a preview section to allow users to quickly glance at the built-in datasets. I believe this would help users choose the appropriate dataset for exploring the table.

### CODE REVIEW

**Review by rich-iannone — APPROVED** [review]
LGTM!

**Comment by machow** [comment]
I wonder if something like [polars.DataFrame.glimpse](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.glimpse.html) could be useful here? I realize these are pandas DataFrames, but glimpse scales so nicely width number of columns 😭

**Comment by jrycw** [comment]
Thanks for sharing this—it’s new to me. 

I like how it uses the row to display information more concisely. I’m fine with either option :).

**Comment by jrycw** [comment]
I've pushed another commit using `polars.DataFrame.glimpse`, and it looks promising—I’m leaning toward this option. 

My only concern is that the preview includes Polars-specific data types, which might be a small hurdle for users more familiar with Pandas.

**Comment by jrycw** [comment]
@rich-iannone and @machow, have we reached a consensus on which format to use for the preview section yet?

**Comment by machow** [comment]
From pairing w/ Rich -- the glimpse approach looks great, thanks for taking the time to explore different approaches here!

**Pull request merged**
